const express = require("express");
const router = express.Router();
const { isAuthenticated } = require("../../controllers/auth.controller");
const customerController = require("../../controllers/adminl-panel/customer.controller");
router.post("/", isAuthenticated, customerController.addCustomer);
router.get("/", isAuthenticated, customerController.getCustomers);
router.get("/:id", isAuthenticated, customerController.getCustomerById);
router.delete("/:id", isAuthenticated, customerController.deleteCustomers);
router.put("/:id", isAuthenticated, customerController.updateCustomers);
module.exports = router;
